version = 0.1

[default.deploy.parameters]
stack_name = "testlambda"
resolve_s3 = true
s3_prefix = "testlambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []
