AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-pythonSetpFunction

  Sample SAM Template for lambda-pythonSetpFunction

Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - x86_64
    Policies:
      - CloudWatchLogsPolicy: {}

Resources:
  SFBackupStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/salesforcebackup.asl.json
      DefinitionSubstitutions:
        CheckBackupStatusArn: !GetAtt CheckBackupStatus.Arn
        DownloadDataToS3Arn: !GetAtt DownloadDataToS3.Arn
        GetSalesforceObjectListArn: !GetAtt GetSalesforceObjectList.Arn
        InitBulkBackupArn: !GetAtt InitBulkBackup.Arn
        UpdateDBStatusCompletedArn: !GetAtt UpdateDBStatusCompleted.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckBackupStatus
        - LambdaInvokePolicy:
            FunctionName: !Ref DownloadDataToS3
        - LambdaInvokePolicy:
            FunctionName: !Ref GetSalesforceObjectList
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateDBStatusCompleted
        - LambdaInvokePolicy:
            FunctionName: !Ref InitBulkBackup
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

  CheckBackupStatus:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/CheckBackupStatus/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64

  DownloadDataToS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/DownloadDataToS3/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64

  GetSalesforceObjectList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/GetSalesforceObjectList/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /initBackup
            Method: POST
        health:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: GET
  UpdateDBStatusCompleted:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/UpdateDBStatusCompleted/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
  InitBulkBackup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/InitBulkBackup/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64

  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  # SFBackupStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  SFBackupStateMachineArn:
    Description: "Stock Trading State machine ARN"
    Value: !Ref SFBackupStateMachine
  SFBackupStateMachineRoleArn:
    Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
    Value: !GetAtt SFBackupStateMachineRole.Arn
